name: Cc.Test

on:
  push:
    paths:
    - '.github/workflows/cc-test.yml'
    branches: [ main, dev ]

jobs:

  test:
    runs-on: [ self-hosted, cherry-cert-lnx ]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Display test message
        run: echo "Cc.Test"
